### ISSUE TITLE
Rename Faculty Advisor on Edit Interface

### ISSUE THREAD

**Issue by jlbooker** [AppStateESS/InternshipInventory#293]
Rename "Faculty Advisor" to "Faculty Supervisor" on the edit internship interface.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/197608637180879/197609667916823)

**Comment by caldwellc1** [comment]
@jlbooker I think this has already been taken care of. The only other places the word Advisor is used in the project is in GradSchoolNotificationEmail.php and UndoDepartmentApprove.php.

**Comment by jlbooker** [comment]
Yep, this is already done.
