### ISSUE TITLE
Background Check Request needs confirmation before execution.

### ISSUE THREAD

**Issue by Stardog** [AppStateESS/InternshipInventory#388]
If clicked by mistake, currently it can only be reversed via the database. Make a way a deity can reverse it.

**Comment by jlbooker** [comment]
@Stardog It only sends an email, so there's not really a way to "reverse" that. I suppose you could send another "just kidding, nevermind" email.

**Comment by Stardog** [comment]
Change to: add confirmation of background email send.

**Comment by caldwellc1** [comment]
Pull Request #461
