### ISSUE TITLE
Administrative Undergraduate Majors list broken

### ISSUE THREAD

**Issue by Stardog** [AppStateESS/InternshipInventory#392]
The list is several rows of blank information.

**Comment by jlbooker** [comment]
@Stardog The majors are pulled from Banner via the `BannerMajorProvider` in https://github.com/AppStateESS/InternshipInventory/tree/master/class/DataProvider/Major. Setting them administratively is a left-over feature from before Banner integration.

Also, I was in the process of unifying the `intern_major` and `intern_grad_prog` tables into just `intern_major` with a `level` field indicating graduate or undergraduate.

You can probably just remove both of the "edit majors" and "edit graduate programs" items from the admin menu and be done with it.
